spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exchangeservice
    
    username: root
    password: root
    
  application:
    name: forex-service

    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
server:
  port: 8000